name: minimal
description: A New Way to Learn the History of Queensland
version: 1.1.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  url_launcher:
  convert:
  http:
  flutter:
    sdk: flutter
  responsive_framework:
  get: ^4.3.8
  google_fonts: ^2.1.0
  animations: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0

flutter_icons:
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/